### ISSUE TITLE
 free logo design for Plex-Music-Viewer

### ISSUE THREAD

**Issue by Pelikens** [JakeStanger/Plex-Music-Viewer#8]
Hi, my name is Ksenia. I'm a graphic designer and I'd like to collaborate on your open source project and propose free logo/icon/favicon design for your project. If it's something you're interested in, please, let me know!

**Comment by JakeStanger** [comment]
Hi, I would certainly be interested in a logo. Thanks for the offer!

**Comment by Pelikens** [comment]
Thanks for your reply! That's great! Do you have any special requirements for the logo? Any symbols that should be included? And how do you plan to use the logo? On your web site and etc?

**Comment by JakeStanger** [comment]
I have plans to make this more generalized than just Plex (local files, MPD database...), and more generalized than just music (TV, Movies...) so I don't have anything specific in mind. It would be used in the actual web app and on supporting sites (github, any documentation).

**Comment by Pelikens** [comment]
and name write Plex-Music-Viewer?

**Comment by JakeStanger** [comment]
Do not worry about a name for now please.

**Comment by Pelikens** [comment]
OK, I'll show you an option as it's ready

**Comment by Pelikens** [comment]
Hi, here is an option for the logo. Please, let me know what do you think?
![image](https://user-images.githubusercontent.com/39441298/43819307-07d661e6-9aeb-11e8-8108-c0abf57577e8.png)
